"""added autoincrement=True

Revision ID: 80f34c1c6268
Revises: 9057673c8baa
Create Date: 2023-03-09 15:01:42.619899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80f34c1c6268'
down_revision = '9057673c8baa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
