"""added Cafe table

Revision ID: 8c2b4b13dd2f
Revises: 29a20b5a01e1
Create Date: 2023-03-09 14:22:05.294553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c2b4b13dd2f'
down_revision = '29a20b5a01e1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
