"""added columns and relationships

Revision ID: 9057673c8baa
Revises: 8c2b4b13dd2f
Create Date: 2023-03-09 14:55:51.444024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9057673c8baa'
down_revision = '8c2b4b13dd2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('cafe_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'drinks', 'drinks', ['cafe_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drinks', type_='foreignkey')
    op.drop_column('drinks', 'cafe_id')
    # ### end Alembic commands ###
